import type { Metadata } from 'next'

import React from 'react'

import Appbar from '@/app/components/Appbar'
import { Providers } from '@/app/components/providers'
import SignInPanel from '@/app/components/signInPanel'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body className={inter.className}>
        <Providers>
          <Appbar>
            <SignInPanel />
          </Appbar>
          {children}
        </Providers>
      </body>
    </html>
  )
}
